#############################################################################
# Makefile for building: libQGphotoCamera.1.0.0.dylib
# Generated by qmake (3.0) (Qt 5.0.2) on: Tue Apr 30 20:03:56 2013
# Project:  QGphotoCamera.pro
# Template: lib
# Command: /Users/bowesjs/Qt5.0.2/5.0.2/clang_64/bin/qmake -o Makefile QGphotoCamera.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQGPHOTOCAMERA_LIBRARY -DNODEPS -D__MINGW__ -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -mmacosx-version-min=10.6 -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -mmacosx-version-min=10.6 -O2 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../../Qt5.0.2/5.0.2/clang_64/mkspecs/macx-clang -I. -I../electrobee/QCameraInterface -I../DcRawQT -I/opt/local/include -I../../Qt5.0.2/5.0.2/clang_64/include -I../../Qt5.0.2/5.0.2/clang_64/include/QtWidgets -I../../Qt5.0.2/5.0.2/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt5.0.2/5.0.2/clang_64/include/QtGui -I../../Qt5.0.2/5.0.2/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt5.0.2/5.0.2/clang_64/include/QtCore -I../../Qt5.0.2/5.0.2/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -mmacosx-version-min=10.6 -single_module -dynamiclib -compatibility_version	1.0 -current_version	1.0.0 -install_name	libQGphotoCamera.1.dylib
LIBS          = $(SUBLIBS) -L../Debug -L/opt/local/lib -lDcRawQT -lQCameraInterface -lgphoto2 -lgphoto2_port -F/Users/bowesjs/Qt5.0.2/5.0.2/clang_64/lib -framework QtWidgets -F/Users/bowesjs/Qt5.0.2/5.0.2/clang_64/qtbase/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/bowesjs/Qt5.0.2/5.0.2/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qgphotocamera.cpp \
		qgphotointerface.cpp moc_qgphotocamera.cpp \
		moc_qgphotointerface.cpp
OBJECTS       = qgphotocamera.o \
		qgphotointerface.o \
		moc_qgphotocamera.o \
		moc_qgphotointerface.o
DIST          = ../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/qdevice.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/unix.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base-macx.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac-minimum-version.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/qconfig.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_v8.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_post.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/default_pre.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/resources.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/moc.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/uic.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/lex.prf \
		QGphotoCamera.pro \
		QGphotoCamera.pro
QMAKE_TARGET  = QGphotoCamera
DESTDIR       = cameras/
TARGET        = libQGphotoCamera.1.0.0.dylib
TARGETA       = cameras/libQGphotoCamera.a
TARGETD       = libQGphotoCamera.1.0.0.dylib
TARGET0       = libQGphotoCamera.dylib
TARGET1       = libQGphotoCamera.1.dylib
TARGET2       = libQGphotoCamera.1.0.dylib

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-mmacosx-version-min=10.6 \
		-O2 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  cameras/$(TARGET)

cameras/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d cameras/ || mkdir -p cameras/
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) cameras/$(TARGET)
	-$(DEL_FILE) cameras/$(TARGET0)
	-$(DEL_FILE) cameras/$(TARGET1)
	-$(DEL_FILE) cameras/$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) cameras/



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)
	$(RANLIB) $(TARGETA)

Makefile: QGphotoCamera.pro ../../Qt5.0.2/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/qdevice.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/unix.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base-macx.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac-minimum-version.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/qconfig.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_v8.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_post.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/default_pre.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/resources.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/moc.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/uic.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/lex.prf \
		QGphotoCamera.pro \
		/Users/bowesjs/Qt5.0.2/5.0.2/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/bowesjs/Qt5.0.2/5.0.2/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/bowesjs/Qt5.0.2/5.0.2/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile QGphotoCamera.pro
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/qdevice.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/device_config.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/shell-unix.conf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/unix.conf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac.conf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base-macx.conf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang.conf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac-minimum-version.conf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/qconfig.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_bootstrap.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_clucene.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_v8.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_post.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/default_pre.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_post.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/resources.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/moc.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/uic.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/yacc.prf:
../../Qt5.0.2/5.0.2/clang_64/mkspecs/features/lex.prf:
QGphotoCamera.pro:
/Users/bowesjs/Qt5.0.2/5.0.2/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/bowesjs/Qt5.0.2/5.0.2/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/bowesjs/Qt5.0.2/5.0.2/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile QGphotoCamera.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/QGphotoCamera1.0.0 || mkdir -p .tmp/QGphotoCamera1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QGphotoCamera1.0.0/ && $(COPY_FILE) --parents qgphotocamera.h qgphotocamera_global.h qgphotointerface.h .tmp/QGphotoCamera1.0.0/ && $(COPY_FILE) --parents qgphotocamera.cpp qgphotointerface.cpp .tmp/QGphotoCamera1.0.0/ && (cd `dirname .tmp/QGphotoCamera1.0.0` && $(TAR) QGphotoCamera1.0.0.tar QGphotoCamera1.0.0 && $(COMPRESS) QGphotoCamera1.0.0.tar) && $(MOVE) `dirname .tmp/QGphotoCamera1.0.0`/QGphotoCamera1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QGphotoCamera1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) cameras/$(TARGET) 
	-$(DEL_FILE) cameras/$(TARGET0) cameras/$(TARGET1) cameras/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_qgphotocamera.cpp moc_qgphotointerface.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qgphotocamera.cpp moc_qgphotointerface.cpp
moc_qgphotocamera.cpp: ../electrobee/QCameraInterface/qcamera.h \
		../electrobee/QCameraInterface/qcamerainterface_global.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qglobal.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qconfig.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfeatures.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QObject \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qobjectdefs.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qnamespace.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstring.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qchar.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qbytearray.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qbasicatomic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_bootstrap.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_arch.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_integrity.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_vxworks.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_powerpc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_alpha.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_arm.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv7.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv6.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv5.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_avr32.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_bfin.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_generic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_i386.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_ia64.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_macosx.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_x86_64.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_mips.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_parisc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_s390.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sparc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_windows.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_windowsce.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_symbian.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sh.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sh4a.h \
		/opt/local/Library/Frameworks/Qt3Support.framework/Versions/4/Headers/q3cstring.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringbuilder.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qmap.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qiterator.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qalgorithms.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qcoreevent.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qscopedpointer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qmetatype.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qdatastream.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qiodevice.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qobject.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/QImage \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/qimage.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qtransform.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qmatrix.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpolygon.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/QPointF \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qpoint.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/QPoint \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qrect.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsize.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qregion.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwindowdefs.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qmacdefines_mac.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwindowdefs_win.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qline.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwmatrix.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpainterpath.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpaintdevice.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qrgb.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringlist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qregexp.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringmatcher.h \
		/opt/local/Library/Frameworks/Qt3Support.framework/Versions/4/Headers/q3valuelist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlinkedlist.h \
		../electrobee/QCameraInterface/qcameraproperties.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QMap \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qpair.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qdebug.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qhash.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qtextstream.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlocale.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qvariant.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qtextcodec.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qset.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qcontiguouscache.h \
		../electrobee/QCameraInterface/qcameraproperty.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QVariant \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qvariant.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QRegExp \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QDir \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qdir.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfileinfo.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfile.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qshareddata.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QFile \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qfile.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qfiledevice.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/QPixmap \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/qpixmap.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qcolor.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsharedpointer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsharedpointer_impl.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qimage.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QBuffer \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qbuffer.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QMutex \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qmutex.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QXmlStreamReader \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qxmlstream.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QXmlStreamAttributes \
		qgphotocamera_global.h \
		/opt/local/include/gphoto2/gphoto2-camera.h \
		/opt/local/include/gphoto2/gphoto2-abilities-list.h \
		/opt/local/include/gphoto2/gphoto2-context.h \
		/opt/local/include/gphoto2/gphoto2-list.h \
		/opt/local/include/gphoto2/gphoto2-port-info-list.h \
		/opt/local/include/gphoto2/gphoto2-port.h \
		/opt/local/include/gphoto2/gphoto2-port-portability.h \
		/opt/local/include/gphoto2/gphoto2-port-log.h \
		/opt/local/include/gphoto2/gphoto2-widget.h \
		/opt/local/include/gphoto2/gphoto2-filesys.h \
		/opt/local/include/gphoto2/gphoto2-file.h \
		/opt/local/include/gphoto2/gphoto2-result.h \
		/opt/local/include/gphoto2/gphoto2-port-result.h \
		qgphotocamera.h
	/Users/bowesjs/Qt5.0.2/5.0.2/clang_64/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 qgphotocamera.h -o moc_qgphotocamera.cpp

moc_qgphotointerface.cpp: ../electrobee/QCameraInterface/qcamerainterface.h \
		../electrobee/QCameraInterface/qcamera.h \
		../electrobee/QCameraInterface/qcamerainterface_global.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qglobal.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qconfig.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfeatures.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QObject \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qobjectdefs.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qnamespace.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstring.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qchar.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qbytearray.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qbasicatomic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_bootstrap.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_arch.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_integrity.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_vxworks.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_powerpc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_alpha.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_arm.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv7.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv6.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv5.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_avr32.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_bfin.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_generic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_i386.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_ia64.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_macosx.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_x86_64.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_mips.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_parisc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_s390.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sparc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_windows.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_windowsce.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_symbian.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sh.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sh4a.h \
		/opt/local/Library/Frameworks/Qt3Support.framework/Versions/4/Headers/q3cstring.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringbuilder.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qmap.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qiterator.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qalgorithms.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qcoreevent.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qscopedpointer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qmetatype.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qdatastream.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qiodevice.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qobject.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/QImage \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/qimage.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qtransform.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qmatrix.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpolygon.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/QPointF \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qpoint.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/QPoint \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qrect.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsize.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qregion.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwindowdefs.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qmacdefines_mac.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwindowdefs_win.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qline.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwmatrix.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpainterpath.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpaintdevice.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qrgb.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringlist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qregexp.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringmatcher.h \
		/opt/local/Library/Frameworks/Qt3Support.framework/Versions/4/Headers/q3valuelist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlinkedlist.h \
		../electrobee/QCameraInterface/qcameraproperties.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QMap \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qpair.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qdebug.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qhash.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qtextstream.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlocale.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qvariant.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qtextcodec.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qset.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qcontiguouscache.h \
		../electrobee/QCameraInterface/qcameraproperty.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QVariant \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qvariant.h \
		qgphotocamera_global.h \
		/opt/local/include/gphoto2/gphoto2-camera.h \
		/opt/local/include/gphoto2/gphoto2-abilities-list.h \
		/opt/local/include/gphoto2/gphoto2-context.h \
		/opt/local/include/gphoto2/gphoto2-list.h \
		/opt/local/include/gphoto2/gphoto2-port-info-list.h \
		/opt/local/include/gphoto2/gphoto2-port.h \
		/opt/local/include/gphoto2/gphoto2-port-portability.h \
		/opt/local/include/gphoto2/gphoto2-port-log.h \
		/opt/local/include/gphoto2/gphoto2-widget.h \
		/opt/local/include/gphoto2/gphoto2-filesys.h \
		/opt/local/include/gphoto2/gphoto2-file.h \
		/opt/local/include/gphoto2/gphoto2-result.h \
		/opt/local/include/gphoto2/gphoto2-port-result.h \
		qgphotocamera.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QRegExp \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QDir \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qdir.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfileinfo.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfile.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qshareddata.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QFile \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qfile.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qfiledevice.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/QPixmap \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/qpixmap.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qcolor.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsharedpointer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsharedpointer_impl.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qimage.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QBuffer \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qbuffer.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QMutex \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qmutex.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QXmlStreamReader \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qxmlstream.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QXmlStreamAttributes \
		qgphotointerface.h
	/Users/bowesjs/Qt5.0.2/5.0.2/clang_64/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 qgphotointerface.h -o moc_qgphotointerface.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

qgphotocamera.o: qgphotocamera.cpp ../DcRawQT/dcrimage.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QObject \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qobjectdefs.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qnamespace.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qglobal.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qconfig.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfeatures.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstring.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qchar.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qbytearray.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qbasicatomic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_bootstrap.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_arch.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_integrity.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_vxworks.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_powerpc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_alpha.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_arm.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv7.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv6.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv5.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_avr32.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_bfin.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_generic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_i386.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_ia64.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_macosx.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_x86_64.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_mips.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_parisc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_s390.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sparc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_windows.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_windowsce.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_symbian.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sh.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sh4a.h \
		/opt/local/Library/Frameworks/Qt3Support.framework/Versions/4/Headers/q3cstring.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringbuilder.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qmap.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qiterator.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qalgorithms.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qcoreevent.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qscopedpointer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qmetatype.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qdatastream.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qiodevice.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qobject.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/QImage \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/qimage.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qtransform.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qmatrix.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpolygon.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/QPointF \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qpoint.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/QPoint \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qrect.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsize.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qregion.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwindowdefs.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qmacdefines_mac.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwindowdefs_win.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qline.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwmatrix.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpainterpath.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpaintdevice.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qrgb.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringlist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qregexp.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringmatcher.h \
		/opt/local/Library/Frameworks/Qt3Support.framework/Versions/4/Headers/q3valuelist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlinkedlist.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/QRgb \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/qrgb.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QQueue \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qqueue.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QMutex \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qmutex.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QRectF \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qrect.h \
		../DcRawQT/dcraw.h \
		/opt/local/include/jasper/jasper.h \
		/opt/local/include/jasper/jas_config.h \
		/opt/local/include/jasper/jas_config2.h \
		/opt/local/include/jasper/jas_types.h \
		/opt/local/include/jasper/jas_version.h \
		/opt/local/include/jasper/jas_init.h \
		/opt/local/include/jasper/jas_cm.h \
		/opt/local/include/jasper/jas_icc.h \
		/opt/local/include/jasper/jas_stream.h \
		/opt/local/include/jasper/jas_fix.h \
		/opt/local/include/jasper/jas_debug.h \
		/opt/local/include/jasper/jas_getopt.h \
		/opt/local/include/jasper/jas_image.h \
		/opt/local/include/jasper/jas_seq.h \
		/opt/local/include/jasper/jas_math.h \
		/opt/local/include/jasper/jas_malloc.h \
		/opt/local/include/jasper/jas_string.h \
		/opt/local/include/jasper/jas_tmr.h \
		/opt/local/include/jasper/jas_tvp.h \
		/opt/local/include/jpeglib.h \
		/opt/local/include/jconfig.h \
		/opt/local/include/jmorecfg.h \
		/opt/local/include/jerror.h \
		/opt/local/include/lcms.h \
		/opt/local/include/icc34.h \
		/opt/local/include/libintl.h \
		../DcRawQT/dcrawqt.h \
		../DcRawQT/dcrawqt_global.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QStringList \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qstringlist.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QSize \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qsize.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtWidgets/QProgressDialog \
		../../Qt5.0.2/5.0.2/clang_64/include/QtWidgets/qprogressdialog.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtWidgets/qdialog.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtWidgets/qwidget.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qmargins.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpalette.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qcolor.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qbrush.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qpair.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qimage.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpixmap.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsharedpointer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qshareddata.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsharedpointer_impl.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qfont.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qfontmetrics.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qfontinfo.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtWidgets/qsizepolicy.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qcursor.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qkeysequence.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qevent.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qmime.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qmimedata.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qvariant.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qhash.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qdrag.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qset.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfile.h \
		../DcRawQT/CImg.h \
		/opt/local/include/X11/Xlib.h \
		/opt/local/include/X11/X.h \
		/opt/local/include/X11/Xmd.h \
		/opt/local/include/X11/Xfuncproto.h \
		/opt/local/include/X11/Xosdefs.h \
		/opt/local/include/X11/Xutil.h \
		/opt/local/include/X11/keysym.h \
		/opt/local/include/X11/keysymdef.h \
		/opt/local/include/X11/extensions/XShm.h \
		/opt/local/include/X11/extensions/shm.h \
		/opt/local/include/X11/extensions/Xrandr.h \
		/opt/local/include/X11/extensions/randr.h \
		/opt/local/include/X11/extensions/Xrender.h \
		/opt/local/include/X11/extensions/render.h \
		/opt/local/include/X11/Xdefs.h \
		/opt/local/include/libpng15/png.h \
		/opt/local/include/libpng15/pnglibconf.h \
		/opt/local/include/libpng15/pngconf.h \
		/opt/local/include/tiffio.h \
		/opt/local/include/tiff.h \
		/opt/local/include/tiffconf.h \
		/opt/local/include/tiffvers.h \
		/opt/local/include/zlib.h \
		/opt/local/include/zconf.h \
		/opt/local/include/fftw3.h \
		qgphotocamera.h \
		../electrobee/QCameraInterface/qcamera.h \
		../electrobee/QCameraInterface/qcamerainterface_global.h \
		../electrobee/QCameraInterface/qcameraproperties.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QMap \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qdebug.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qtextstream.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlocale.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qtextcodec.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qcontiguouscache.h \
		../electrobee/QCameraInterface/qcameraproperty.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QVariant \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qvariant.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QRegExp \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QDir \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qdir.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfileinfo.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QFile \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qfile.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qfiledevice.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/QPixmap \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/qpixmap.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QBuffer \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qbuffer.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QXmlStreamReader \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qxmlstream.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QXmlStreamAttributes \
		qgphotocamera_global.h \
		/opt/local/include/gphoto2/gphoto2-camera.h \
		/opt/local/include/gphoto2/gphoto2-abilities-list.h \
		/opt/local/include/gphoto2/gphoto2-context.h \
		/opt/local/include/gphoto2/gphoto2-list.h \
		/opt/local/include/gphoto2/gphoto2-port-info-list.h \
		/opt/local/include/gphoto2/gphoto2-port.h \
		/opt/local/include/gphoto2/gphoto2-port-portability.h \
		/opt/local/include/gphoto2/gphoto2-port-log.h \
		/opt/local/include/gphoto2/gphoto2-widget.h \
		/opt/local/include/gphoto2/gphoto2-filesys.h \
		/opt/local/include/gphoto2/gphoto2-file.h \
		/opt/local/include/gphoto2/gphoto2-result.h \
		/opt/local/include/gphoto2/gphoto2-port-result.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qgphotocamera.o qgphotocamera.cpp

qgphotointerface.o: qgphotointerface.cpp qgphotointerface.h \
		../electrobee/QCameraInterface/qcamerainterface.h \
		../electrobee/QCameraInterface/qcamera.h \
		../electrobee/QCameraInterface/qcamerainterface_global.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qglobal.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qconfig.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfeatures.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QObject \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qobjectdefs.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qnamespace.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstring.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qchar.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qbytearray.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qbasicatomic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_bootstrap.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_arch.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_integrity.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_vxworks.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_powerpc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_alpha.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_arm.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv7.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv6.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_armv5.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_avr32.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_bfin.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_generic.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_i386.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_ia64.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_macosx.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_x86_64.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_mips.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_parisc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_s390.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sparc.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_windows.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_windowsce.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_symbian.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sh.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qatomic_sh4a.h \
		/opt/local/Library/Frameworks/Qt3Support.framework/Versions/4/Headers/q3cstring.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringbuilder.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qmap.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qiterator.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qalgorithms.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qcoreevent.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qscopedpointer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qmetatype.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qdatastream.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qiodevice.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qobject.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/QImage \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/qimage.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qtransform.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qmatrix.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpolygon.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qvector.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/QPointF \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qpoint.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/QPoint \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qrect.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsize.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qregion.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwindowdefs.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qmacdefines_mac.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwindowdefs_win.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qline.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qwmatrix.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpainterpath.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qpaintdevice.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qrgb.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringlist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qregexp.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qstringmatcher.h \
		/opt/local/Library/Frameworks/Qt3Support.framework/Versions/4/Headers/q3valuelist.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlinkedlist.h \
		../electrobee/QCameraInterface/qcameraproperties.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QMap \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qpair.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qdebug.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qhash.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qtextstream.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qlocale.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qvariant.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qtextcodec.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qset.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qcontiguouscache.h \
		../electrobee/QCameraInterface/qcameraproperty.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QVariant \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qvariant.h \
		qgphotocamera_global.h \
		/opt/local/include/gphoto2/gphoto2-camera.h \
		/opt/local/include/gphoto2/gphoto2-abilities-list.h \
		/opt/local/include/gphoto2/gphoto2-context.h \
		/opt/local/include/gphoto2/gphoto2-list.h \
		/opt/local/include/gphoto2/gphoto2-port-info-list.h \
		/opt/local/include/gphoto2/gphoto2-port.h \
		/opt/local/include/gphoto2/gphoto2-port-portability.h \
		/opt/local/include/gphoto2/gphoto2-port-log.h \
		/opt/local/include/gphoto2/gphoto2-widget.h \
		/opt/local/include/gphoto2/gphoto2-filesys.h \
		/opt/local/include/gphoto2/gphoto2-file.h \
		/opt/local/include/gphoto2/gphoto2-result.h \
		/opt/local/include/gphoto2/gphoto2-port-result.h \
		qgphotocamera.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QRegExp \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QDir \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qdir.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfileinfo.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qfile.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qshareddata.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QFile \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qfile.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qfiledevice.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/QPixmap \
		../../Qt5.0.2/5.0.2/clang_64/include/QtGui/qpixmap.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qcolor.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsharedpointer.h \
		/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers/qsharedpointer_impl.h \
		/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers/qimage.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QBuffer \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qbuffer.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QMutex \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qmutex.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QXmlStreamReader \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/qxmlstream.h \
		../../Qt5.0.2/5.0.2/clang_64/include/QtCore/QXmlStreamAttributes
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qgphotointerface.o qgphotointerface.cpp

moc_qgphotocamera.o: moc_qgphotocamera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qgphotocamera.o moc_qgphotocamera.cpp

moc_qgphotointerface.o: moc_qgphotointerface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qgphotointerface.o moc_qgphotointerface.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(INSTALL_PROGRAM) "cameras/$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET0)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET1)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET2)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET0)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET1)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET2)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

